-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE ca_daily_actor_edits (
  cad_date TEXT NOT NULL,
  cad_actor BIGINT NOT NULL,
  cad_actor_user INT DEFAULT NULL,
  cad_edit_count INT NOT NULL,
  PRIMARY KEY(cad_date, cad_actor)
);

CREATE INDEX cad_actor_date ON ca_daily_actor_edits (cad_actor, cad_date);

CREATE INDEX cad_date_actor_user ON ca_daily_actor_edits (cad_date, cad_actor_user);
