-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ca_daily_actor_edits (
  cad_date VARBINARY(8) NOT NULL,
  cad_actor BIGINT UNSIGNED NOT NULL,
  cad_actor_user INT UNSIGNED DEFAULT NULL,
  cad_edit_count INT UNSIGNED NOT NULL,
  INDEX cad_actor_date (cad_actor, cad_date),
  INDEX cad_date_actor_user (cad_date, cad_actor_user),
  PRIMARY KEY(cad_date, cad_actor)
) /*$wgDBTableOptions*/;
